version: '3.9'
services:
  postgres:
    image: postgres:17
    container_name: szfm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SZFM
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alma1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - szfm-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: szfm-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: SZFM
      DB_USERNAME: postgres
      DB_PASSWORD: Alma1234
    depends_on:
      - postgres
    networks:
      - szfm-network

networks:
  szfm-network:
    driver: bridge

volumes:
  postgres-data:
